#' CRU TS 4.04 Landmask dataset
#'
#' A dataset containing information of land mask with a grid of 0.5 by 0.5
#' degrees resolution. \code{TRUE} values represent a land grid cell.
#'
#' The mask was generated by looking at the values of \code{tmn} and \code{vap},
#' for each grid cell, if at least one timestep had a non-missing value, then
#' the entire grid cell was marked as a land grid cell.
#'
#' @format A 2D matrix of 720 x 360 (lon x lat) with boolean values:
#' \describe{
#'     \item{\code{TRUE}}{Land grid cell.}
#'     \item{\code{FALSE}}{Non-land grid cell.}
#' }
#'
#' @usage data(land_mask)
#' @references
#' University of East Anglia Climatic Research Unit; Harris, I.C.; Jones, P.D.;
#' Osborn, T. (2020): CRU TS4.04: Climatic Research Unit (CRU) Time-Series (TS)
#' version 4.04 of high-resolution gridded data of month-by-month variation in
#' climate (Jan. 1901- Dec. 2019). Centre for Environmental Data Analysis.
#' <https://catalogue.ceda.ac.uk/uuid/89e1e34ec3554dc98594a5732622bce9>
#' @keywords datasets internal
"land_mask"

#' Antarctic Ice Cores Revised 800KYr CO2 dataset
#'
#' A dataset containing information of Antarctic ice cores revised 800KYr CO2.
#'
#' @details Revised EPICA Dome C and Antarctic composite ice core atmospheric
#' CO2 data. This new version of CO2 composite replaces the old version of
#' Luthi et al. (2008), which contains the analytical bias described in
#' Bereiter et al. 2015 and lower quality data in other sections. For details
#' about the improvements relative to the previous version see supplementary
#' information of Bereiter et al. 2015. For detailed references of all records
#' refer to the supplemetary information of Bereiter et al. 2015. For latest
#' anthropogenic data refer to NOAA/Mauna Loa record. Age unit is in years
#' before present (yr BP) where present refers to 1950 AD. Note, not all
#' records shown in Excel worksheet "all records" are part of the composite.
#'
#' @section Notes:
#' Composite built from the following:
#' \itemize{
#' \item -51-1800 yr BP: Law Dome (Rubino et al., 2013)
#' \item 1.8-2 kyr BP:	Law Dome (MacFarling Meure et al., 2006)
#' \item 2-11 kyr BP:	Dome C (Monnin et al., 2001 + 2004)
#' \item 11-22 kyr BP:	WAIS (Marcott et al., 2014) minus 4 ppmv (see text)
#' \item 22-40 kyr BP:	Siple Dome (Ahn et al., 2014)
#' \item 40-60 kyr BP:	TALDICE (Bereiter et al., 2012)
#' \item 60-115 kyr BP:	EDML (Bereiter et al., 2012)
#' \item 105-155 kyr BP:	Dome C Sublimation (Schneider et al., 2013)
#' \item 155-393 kyr BP:	Vostok (Petit et al., 1999)
#' \item 393-611 kyr BP:	Dome C (Siegenthaler et al., 2005)
#' \item 612-800 kyr BP:	Dome C (Bereiter et al., 2014)
#' }
#'
#' If millennial scale or smaller details of the composite are studied, we
#' recommend to look into all records available	for that period and not only in
#' the composite.
#'
#' @format A data frame with 1901 rows and 3 variables, each description has
#' 9 components: what, material, error, units, seasonality, archive, detail,
#' method, C or N for Character or Numeric data.
#' \describe{
#'     \item{age_gas_calBP}{age, gas, , calendar years before present, , , ,
#'     AICC2012 except for Law Dome WAIS and Siple Dome, N.}
#'     \item{co2_ppm}{CO2 concentration, , , ppmv, , , corrected, , N}
#'     \item{co2_1s_ppm}{CO2 concentration sigma mean, , , ppmv, , , Where no
#'     individual sigma is given we use average for system/record, , N}
#' }
#'
#' @usage data(ice_core)
#' @source \url{ftp://ftp.ncdc.noaa.gov/pub/data/paleo/icecore/antarctica/antarctica2015co2composite.txt}
#' @author Bernhard Bereiter \email{bbereiter@ucsd.edu}
#' @author Sarah Eggleston
#' @author Jochen Schmitt
#' @author Christoph Nehrbass-Ahles
#' @author Thomas F. Stocker
#' @author Hubertus Fischer
#' @author Sepp Kipfstuhl
#' @author Jerome Chappellaz
#' @references
#' Bereiter, B., Eggleston, S., Schmitt, J., Nehrbass‐Ahles, C., Stocker, T. F.,
#' Fischer, H., Kipfstuhl, S., and Chappellaz, J. (2015), Revision of the EPICA
#' Dome C CO2 record from 800 to 600 kyr before present, Geophys. Res. Lett.,
#' 42, 542– 549, <doi:10.1002/2014GL061957>.
#' @keywords datasets internal
"ice_core"

#' Latitude dataset
#'
#' A dataset containing information of the latitude dimension at a resolution
#' of 0.5 deg.
#'
#' @format A list with 4 elements:
#' \describe{
#'     \item{data}{Numeric vector with the latitude values.}
#'     \item{id}{Identifier to use in netCDF files.}
#'     \item{longname}{String with long name of the variable.}
#'     \item{units}{Latitude units.}
#' }
#'
#' @usage data(lat)
#' @keywords datasets internal
"lat"

#' Longitude dataset
#'
#' A dataset containing information of the longitude dimension at a resolution
#' of 0.5 deg.
#'
#' @format A list with 4 elements:
#' \describe{
#'     \item{data}{Numeric vector with the longitude values.}
#'     \item{id}{Identifier to use in netCDF files.}
#'     \item{longname}{String with long name of the variable.}
#'     \item{units}{Longitude units.}
#' }
#'
#' @usage data(lon)
#' @keywords datasets internal
"lon"
