---
title: "Cloud coverage (`cld`) and VPD"
output:
  pdf_document:
    extra_dependencies:
    - float
    - longtable
  html_document:
    df_print: paged
  github_document:
    pandoc_args: --webtex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  dpi = 300, 
  out.width = "100%",
  comment = "#>",
  fig.path = "man/figures/cld-vpd_",
  fig.width = 12,
  fig.height = 6,
  fig.pos = "!H", 
  out.extra = ""
)

options(knitr.table.format = function() {
  if (knitr::is_latex_output()) 'latex' else 'pandoc'
})

# Set path to working directory
path <- "~/Desktop/iCloud/UoR/Data/CRU/4.04/"

`%>%` <- magrittr::`%>%`

ALPHA <- 0.25
```

```{r, include=knitr::is_latex_output(), echo = FALSE}
knitr::asis_output('\n\n\\renewcommand{\\arraystretch}{1.5}')
```

```{r, eval = TRUE, echo = FALSE}
path <- "~/OneDrive - University of Reading/UoR/Data/CRU/4.04/"
cld <- codos:::nc_var_get(file.path(path, "cru_ts4.04.1901.2019.cld.dat-clim-1961-1990-int.nc"), "cld")$data
cld <- rowMeans(cld, dims = 2)
# sf <- 1 - cld / 100
elv <- codos:::nc_var_get(file.path(path, "halfdeg.elv.nc"), "elv")$data
mi <- codos:::nc_var_get(file.path(path, "cru_ts4.04-clim-1961-1990-mi.nc"), "mi")$data
Tmp <- codos:::nc_var_get(file.path(path, "cru_ts4.04-clim-1961-1990-daily.tmp-gs.nc"), "tmp")$data
vpd <- codos:::nc_var_get(file.path(path, "cru_ts4.04-clim-1961-1990-vpd-tmp-gs.nc"), "vpd")$data

# Apply ice mask
cld[codos:::ice_mask] <- NA
mi[codos:::ice_mask] <- NA
Tmp[codos:::ice_mask] <- NA
vpd[codos:::ice_mask] <- NA
lat <- codos::lat
lon <- codos::lon
lat_lon <- data.frame(i = seq_len(length(lon$data)),
                      j = rep(seq_along(lat$data), each = length(lon$data)))

# cld[Tmp < 5] <- NA
# mi[Tmp < 5] <- NA
# Tmp[Tmp < 5] <- NA
```

```{r, echo = FALSE}
# Cloud coverage
cld_cat <- 
  ifelse(is.na(cld), "UNK",
    ifelse(cld >= 0 & cld <= 10, "0-10",
      ifelse(cld > 10 & cld <= 20, "10-20",
        ifelse(cld > 20 & cld <= 30, "20-30",
          ifelse(cld > 30 & cld <= 40, "30-40",
            ifelse(cld > 40 & cld <= 50, "40-50",
              ifelse(cld > 50 & cld <= 60, "50-60",
                ifelse(cld > 60 & cld <= 70, "60-70",
                  ifelse(cld > 70 & cld <= 80, "70-80",
                    ifelse(cld > 80 & cld <= 90, "80-90", "90-100"))))))))))
cld_long <- matrix(cld, nrow = 1, byrow = TRUE)
cld_long_cat <- matrix(cld_cat, nrow = 1, byrow = TRUE)

# Moisture index
mi_cat <- ifelse(is.na(mi), "UNK", 
            ifelse(mi >= 0 & mi <= 0.5, "0-0.5",
              ifelse(mi > 0.5 & mi <= 1, "0.5-1",
                ifelse(mi > 1 & mi <= 1.5, "1-1.5",
                  ifelse(mi > 1.5 & mi < 2, "1.5-2", "2+")))))
mi_long <- matrix(mi, nrow = 1, byrow = TRUE)
mi_long_cat <- matrix(mi_cat, nrow = 1, byrow = TRUE)

# Temperature
Tmp_cat <- ifelse(is.na(Tmp), "UNK",
            ifelse(Tmp >= 0 & Tmp <= 5, "0-5",
              ifelse(Tmp > 5 & Tmp <= 10, "5-10",
                ifelse(Tmp > 10 & Tmp <= 15, "10-15",
                  ifelse(Tmp > 15 & Tmp <= 20, "15-20",
                    ifelse(Tmp > 20 & Tmp <= 25, "20-25",
                      ifelse(Tmp > 25 & Tmp <= 30, "25-30",
                        ifelse(Tmp > 30 & Tmp <= 35, "30-35", "35+"))))))))
Tmp_long <- matrix(Tmp, nrow = 1, byrow = TRUE)
Tmp_long_cat <- matrix(Tmp_cat, nrow = 1, byrow = TRUE)
vpd_long <- matrix(vpd, nrow = 1, byrow = TRUE)

# Assemble data frame
df <- tibble::tibble(CLD = cld_long[1, ],
                     MI = mi_long[1, ],
                     Tmp = Tmp_long[1, ], 
                     vpd = vpd_long[1, ],
                     cld = as.factor(cld_long_cat[1, ]),
                     mi = as.factor(mi_long_cat[1, ]),
                     tmp = factor(Tmp_long_cat[1, ], c("0-5", "5-10", "10-15", 
                                                     "15-20", "20-25", "25-30", 
                                                     "30-35", "35+", "UNK")))

# Filter rows with all NAs
df <- df %>%
  dplyr::filter(!is.na(CLD),
                !is.na(MI),
                !is.na(Tmp),
                !is.na(vpd))
```

```{r, echo = FALSE}
# Subset data
set.seed(1)
idx <- sample(seq_len(nrow(df)), size = floor(nrow(df) * 0.7), replace = FALSE)
df_train <- df[idx, ]
df_test <- df[-idx, ]
```

## Cloud coverage (`cld`)

##### Linear regression

```{r, include=knitr::is_latex_output(), echo = FALSE}
knitr::asis_output('\n\n\\hfill\\break')
```

```{r cld-mi-lm-all_fig, echo = FALSE, eval = TRUE}
# Start with a simple model to find the start points
model <- lm(CLD ~ MI, df_train)

lmod <- lm(log(CLD) ~ MI,# poly(Tmp, 2) + poly(MI, 2),
           data = df_train)

# Build the model
model <- nls(CLD ~ a + b * (1 - exp(-kMI * MI)),
             df_train,
             start = list(a = 0.1,
                          kMI = 0.001,
                          b = 0.5),
             control = list(maxiter = 1000,
                            minFactor = 1e-10))

# Make predictions
predictions <- predict(model, df_test)
# Model performance
knitr::kable(data.frame(
  RMSE = caret::RMSE(predictions, df_test$CLD),
  R2 = caret::R2(predictions, df_test$CLD)
))

MI_test <- seq(0, max(df$MI), 0.1)
co <- coefficients(model)
df2 <- 
  tibble::tibble(x = MI_test,
                 y = MI_test %>%
                   purrr::map(~co[1] + co[3] * (1 - exp(-co[2] * .x))) %>% 
                   purrr::flatten_dbl()) %>%
  dplyr::filter(y >= 0 & y <= 100)

ggplot2::ggplot(df_train, ggplot2::aes(MI, CLD)) +
  ggplot2::geom_point(ggplot2::aes(colour = tmp), alpha = ALPHA) +
  ggplot2::geom_line(data = df2, ggplot2::aes(x = x, y = y)) +
  ggplot2::geom_point(data = df2, ggplot2::aes(x = x, y = y)) +
  ggplot2::scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
  ggplot2::labs(title = paste0("cld = ",
                               round(co[1], 3),
                               ifelse(co[3] >= 0, " + ", " - "),
                               abs(round(co[3], 3)),
                               " [1 - exp(",
                               ifelse(co[2] >= 0, " ", "- "),
                               abs(round(co[2], 3)),
                               " MI)]"),
                x = "MI [-]", y = "cld [%]") +
  ggplot2::scale_color_brewer(name = "Tmp [째C]",
                              palette = "Spectral",
                              direction = -1) +
  ggplot2::theme_bw()

summary(model)
```

```{r, include=knitr::is_latex_output(), echo = FALSE}
knitr::asis_output('\n\n\\newpage')
```

##### Linear regression ($T_\texttt{C} \ge 5$)

```{r, include=knitr::is_latex_output(), echo = FALSE}
knitr::asis_output('\n\n\\hfill\\break')
```

```{r cld-mi-lm-tmp-greater-than-five_fig, echo = FALSE, eval = TRUE}
df_train5 <- df_train %>%
  dplyr::filter(Tmp >= 5)

# Start with a simple model to find the start points
model <- lm(CLD ~ MI, df_train5)

lmod <- lm(log(CLD) ~ MI,# poly(Tmp, 2) + poly(MI, 2),
           data = df_train5)

# Build the model
model <- nls(CLD ~ a + b * (1 - exp(-kMI * MI)),
             df_train5,
             start = list(a = 0.1,
                          kMI = 0.001,
                          b = 0.5),
              control = list(maxiter = 1000,
                             minFactor = 1e-10))

# Make predictions
predictions <- predict(model, df_test)
# Model performance
knitr::kable(data.frame(
  RMSE = caret::RMSE(predictions, df_test$CLD),
  R2 = caret::R2(predictions, df_test$CLD)
))

MI_test <- seq(0, max(df$MI), 0.1)

co <- coefficients(model)
df2 <- 
  tibble::tibble(x = MI_test,
                 y = MI_test %>%
                   purrr::map(~co[1] + co[3] * (1 - exp(-co[2] * .x))) %>% 
                   purrr::flatten_dbl()) %>%
  dplyr::filter(y >= 0 & y <= 100)

ggplot2::ggplot(df_train5, ggplot2::aes(MI, CLD)) +
  ggplot2::geom_point(ggplot2::aes(colour = tmp), alpha = ALPHA) +
  ggplot2::geom_line(data = df2, ggplot2::aes(x = x, y = y)) +
  ggplot2::geom_point(data = df2, ggplot2::aes(x = x, y = y)) +
  ggplot2::scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
  ggplot2::labs(title = paste0("cld = ",
                               round(co[1], 3),
                               ifelse(co[3] >= 0, " + ", " - "),
                               abs(round(co[3], 3)),
                               " [1 - exp(",
                               ifelse(co[2] >= 0, " ", "- "),
                               abs(round(co[2], 3)),
                               " MI)]"),
                x = "MI [-]", y = "cld [%]") +
  ggplot2::scale_color_brewer(name = "Tmp [째C]",
                              palette = "Spectral",
                              direction = -1) +
  ggplot2::theme_bw()

summary(model)
```

```{r, include=knitr::is_latex_output(), echo = FALSE}
knitr::asis_output('\n\n\\newpage')
```

## Growing season VPD
```{r, eval = TRUE, echo = FALSE}
path <- "~/OneDrive - University of Reading//UoR/Data/CRU/4.04/"
mi <- codos:::nc_var_get(file.path(path, "cru_ts4.04-clim-1961-1990-mi.nc"), "mi")$data
Tmp <- codos:::nc_var_get(file.path(path, "cru_ts4.04-clim-1961-1990-daily.tmp-gs.nc"), "tmp")$data
vpd <- codos:::nc_var_get(file.path(path, "cru_ts4.04-clim-1961-1990-vpd-tmp-gs.nc"), "vpd")$data

# Lat-lon mask
lat <- codos::lat
lon <- codos::lon
lat_lon <- data.frame(i = seq_len(length(lon$data)),
                      j = rep(seq_along(lat$data), each = length(lon$data)))

# Plot variables before applying the ice mask
# image(lon$data, lat$data, mi)
# image(lon$data, lat$data, Tmp)
# image(lon$data, lat$data, vpd)

# Apply ice mask
mi[codos:::ice_mask] <- NA
Tmp[codos:::ice_mask] <- NA
vpd[codos:::ice_mask] <- NA
mi[Tmp < 5] <- NA
Tmp[Tmp < 5] <- NA
```

```{r, echo = FALSE}
mi_cat <- ifelse(is.na(mi), "UNK", 
            ifelse(mi >= 0 & mi <= 0.5, "0-0.5",
              ifelse(mi > 0.5 & mi <= 1, "0.5-1",
                ifelse(mi > 1 & mi <= 1.5, "1-1.5",
                  ifelse(mi > 1.5 & mi < 2, "1.5-2", "2+")))))

mi_long <- matrix(mi, nrow = 1, byrow = TRUE)
mi_long_cat <- matrix(mi_cat, nrow = 1, byrow = TRUE)
Tmp_cat <- ifelse(is.na(Tmp), "UNK",
            ifelse(Tmp >= 0 & Tmp <= 5, "0-5",
              ifelse(Tmp > 5 & Tmp <= 10, "5-10",
                ifelse(Tmp > 10 & Tmp <= 15, "10-15",
                  ifelse(Tmp > 15 & Tmp <= 20, "15-20",
                    ifelse(Tmp > 20 & Tmp <= 25, "20-25",
                      ifelse(Tmp > 25 & Tmp <= 30, "25-30",
                        ifelse(Tmp > 30 & Tmp <= 35, "30-35", "35+"))))))))
Tmp_long <- matrix(Tmp, nrow = 1, byrow = TRUE)
Tmp_long_cat <- matrix(Tmp_cat, nrow = 1, byrow = TRUE)
vpd_long <- matrix(vpd, nrow = 1, byrow = TRUE)
df <- data.frame(Tmp = Tmp_long[1, ], 
                 vpd = vpd_long[1, ],
                 MI = mi_long[1, ],
                 mi = as.factor(mi_long_cat[1, ]),
                 tmp = factor(Tmp_long_cat[1, ], c("0-5", "5-10", "10-15", 
                                                 "15-20", "20-25", "25-30", 
                                                 "30-35", "35+", "UNK")))
```

```{r, echo = FALSE}
df <- df[!is.na(df$Tmp) & !is.na(df$vpd) & !is.na(df$MI), ]

# Subset data
set.seed(1)
idx <- sample(seq_len(nrow(df)), size = floor(nrow(df) * 0.7), replace = FALSE)
df_train <- df[idx, ]
df_test <- df[-idx, ]
```

```{r, echo = FALSE}
## Start with a simple model to find the start points
lmod2 <- lm(log(vpd) ~ Tmp + MI,# poly(Tmp, 2) + poly(MI, 2),
           data = df_train)

model2b <- nls(vpd ~ a * exp(kTmp * Tmp - kMI * MI),
              df_train,
              start = list(a = exp(coef(lmod2)[1]),
                           kTmp = coef(lmod2)[2],
                           kMI = coef(lmod2)[3]),
              control = list(maxiter = 200))

a <- coef(model2b)[1]
kTmp <- coef(model2b)[2]
kMI <- coef(model2b)[3]
summary(model2b)
```

```{r vpd-mi_fig, echo = FALSE}
mi_test <- seq(0, 6.6, 0.1)
tmp_labels <- c("5-10", "10-15", "15-20", "20-25", "25-30", "30-35")
tmp_test <- c(7.5, 12.5, 17.5, 22.5, 27.5, 32.5)
df5 <- data.frame(x = rep(mi_test, length(tmp_test)),
                  y = unlist(lapply(tmp_test,
                                    function(x) (a * exp(kTmp[1] * x - kMI[1] * mi_test)))),
                  z = rep(tmp_labels,
                          each = length(mi_test)))
ggplot2::ggplot(df, ggplot2::aes(MI, vpd)) +
  ggplot2::geom_point(ggplot2::aes(color = tmp), alpha = 0.5) +
  ggplot2::geom_line(data = df5, ggplot2::aes(x = x, y = y, color = z)) +
  ggplot2::geom_point(data = df5, ggplot2::aes(x = x, y = y)) +
  # ggplot2::geom_point(ggplot2::aes(y = vpd_calc, color = tmp), alpha = 0.3) +
  ggplot2::labs(title = paste0("vpd = ",
                               round(a, 3),
                               " exp(",
                               round(kTmp, 3),
                               " Tmp - ",
                               round(kMI, 3),
                               " MI)"),
                x = "MI [-]", y = "vpd [hPa]") +
  ggplot2::scale_color_brewer(name = "Tmp [째C]",
                              palette = "Spectral", 
                              direction = -1) +
  ggplot2::theme_bw()
```

```{r vpd-tmp_fig, echo = FALSE}
mi_labels <- c("0-0.5", "0.5-1", "1-1.5", "1.5-2", "2+")
mi_test <- c(0.25, 0.75, 1.25, 1.75, 2.25)
tmp_test <- seq(5, 35, 1)
df6 <- data.frame(x = rep(tmp_test, length(mi_test)),
                  y = unlist(lapply(mi_test,
                                    function(x) a[1] * exp(kTmp[1] * tmp_test - kMI[1] * x))),
                  z = rep(mi_labels,
                          each = length(tmp_test)))
ggplot2::ggplot(df, ggplot2::aes(Tmp, vpd)) +
  ggplot2::geom_point(ggplot2::aes(color = mi), alpha = 0.5) +
  ggplot2::geom_line(data = df6, ggplot2::aes(x = x, y = y, color = z)) +
  ggplot2::geom_point(data = df6, ggplot2::aes(x = x, y = y)) +
  ggplot2::labs(title = paste0("vpd = ",
                               round(a, 3),
                               " exp(",
                               round(kTmp, 3),
                               " Tmp - ",
                               round(kMI, 3),
                               " MI)"),
                x = "Tmp [째C]", y = "vpd [hPa]") +
  ggplot2::scale_color_brewer(name = "MI [-]", 
                              palette = "Spectral", 
                              direction = -1) +
  ggplot2::theme_bw()
```
