---
title: "SPLASH v2.0.0: tests"
output: 
  pdf_document:
    extra_dependencies: ["float", "longtable"]
    latex_engine: xelatex
  github_document:
    pandoc_args: --webtex
    always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  dpi = 500, 
  out.width = "100%",
  comment = "#>",
  fig.path = "man/figures/splash-v2.0.0-",
  fig.width = 12,
  fig.height = 6,
  fig.pos = "!H", 
  out.extra = ""
)

options(knitr.kable.NA = '',
        knitr.kable.format = "pandoc")

# options(knitr.table.format = function() {
#   if (knitr::is_latex_output()) 'latex' else 'pandoc'
# })

# Set path to working directory
# path <- "~/Desktop/iCloud/UoR/Data/CRU/4.04/"
path <- "~/OneDrive - University of Reading/UoR/Data/CRU/4.04/"

# Load padul data
padul <- readr::read_csv("~/OneDrive - University of Reading/UoR/Data/padul.csv")

`%>%` <- magrittr::`%>%`
`%$%` <- magrittr::`%$%`
ref_idx <- 5:9
```

<!-- ### Test `rsplash` -->
```{r, echo = FALSE, eval = FALSE}
data(Bourne, package = "rsplash")
run1 <- Bourne %$% 
  rsplash::splash.point(
    sw_in = forcing$sw_in, # shortwave radiation W/m2
    tc = forcing$Ta,		   # air temperature C
    pn = forcing$P, # precipitation mm
    lat = md$latitude,		 # latitude deg
    elev = md$elev_m,		   # elevation masl
    slop = md$slop_250m,	 # slope deg
    asp = md$asp_250m,		 # aspect deg
    soil_data = soil, 		 # soil data: sand,clay,som in w/w %. Gravel v/v %, bulk density g/cm3, and depth to the bedrock (m)**
    Au = md$Aups_250m,		 # upslope area m2
    resolution = 250.0  	 # resolution pixel dem used to get Au
  )
```

<!-- Convert XTS object to `tsibble`: -->
```{r, echo = FALSE, eval = FALSE}
forcing2 <- Bourne$forcing %>%
  tsbox::ts_tsibble()
```

```{r, echo = FALSE}
padul <- padul %>%
  dplyr::mutate(Tmean = (T_jja + T_djf) / 2,
                Tmax = Tmean + (T_jja - Tmean) / 0.9,
                Tmin = Tmean + (T_djf - Tmean) / 0.9)

padul_modern <- padul %>%
  dplyr::slice(ref_idx) %>%
  dplyr::select(-1) %>%
  dplyr::summarise(dplyr::across(dplyr::everything(), mean))

padul_anomalies <- seq_len(nrow(padul)) %>%
  purrr::map(~codos::int_sin(padul$Tmin[.x] - padul_modern$Tmin,
                             padul$Tmax[.x] - padul_modern$Tmax))

elv <- codos:::nc_var_get(file.path(path, "halfdeg.elv.nc"), 
                          "elv")
cld <- codos:::nc_var_get(file.path(path, "cru_ts4.04.1901.2019.cld.dat-clim-1961-1990-int.nc"), 
                          "cld")$data
tmp <- codos:::nc_var_get(file.path(path, "cru_ts4.04.1901.2019.daily.tmp.nc"), 
                          "tmp")$data
pre <- codos:::nc_var_get(file.path(path, "cru_ts4.04.1901.2019.pre.dat-new-clim-1961-1990-int.nc"),
                          "pre")$data
sf <- 1 - cld / 100

# Extract the nearest 4 grid cells
idx_y <- which.min(abs(codos::lat$data - 37.0108))
idx_x <- which.min(abs(codos::lon$data + 3.6039))

# Extract elevation subset
padul_elv <- elv$data[c(idx_x, idx_x + 1), c(idx_y - 1, idx_y)]
rownames(padul_elv) <- codos::lat$data[c(idx_y, idx_y - 1)]
colnames(padul_elv) <- codos::lon$data[c(idx_x, idx_x + 1)]
padul_elv <- mean(padul_elv)

# Extract sunshine fraction subset
padul_sf <- sf[c(idx_x, idx_x + 1), c(idx_y - 1, idx_y), ]
rownames(padul_sf) <- codos::lat$data[c(idx_y, idx_y - 1)]
colnames(padul_sf) <- codos::lon$data[c(idx_x, idx_x + 1)]
padul_sf <- colMeans(padul_sf, dims = 2)

# Extract cloud coverage subset
padul_cld <- cld[c(idx_x, idx_x + 1), c(idx_y - 1, idx_y), ]
rownames(padul_cld) <- codos::lat$data[c(idx_y, idx_y - 1)]
colnames(padul_cld) <- codos::lon$data[c(idx_x, idx_x + 1)]
padul_cld <- colMeans(padul_cld, dims = 2)

# Extract temperature subset
padul_tmp <- tmp[c(idx_x, idx_x + 1), c(idx_y - 1, idx_y), ]
rownames(padul_tmp) <- codos::lat$data[c(idx_y, idx_y - 1)]
colnames(padul_tmp) <- codos::lon$data[c(idx_x, idx_x + 1)]
padul_tmp <- colMeans(padul_tmp, dims = 2)

# Extract precipitation subset
padul_pre <- pre[c(idx_x, idx_x + 1), c(idx_y - 1, idx_y), ]
rownames(padul_pre) <- codos::lat$data[c(idx_y, idx_y - 1)]
colnames(padul_pre) <- codos::lon$data[c(idx_x, idx_x + 1)]
padul_pre <- colMeans(padul_pre, dims = 2)
```

```{r, echo = FALSE}
# Delete large objects from the environment
rm(elv, cld, pre, sf, tmp)
```

## Padul PET
### SPLASH v1.0.0
```{r, cache = TRUE}
year <- 1961
padul_pet_splashv1 <- c(1, 179, 247) %>%
  purrr::map(function(k) {
    purrr::map_dbl(seq_len(365),
                   function(i) {
                     splash::calc_daily_evap(lat = 37.0108,
                                             n = i,
                                             elv = padul_elv,
                                             y = year,
                                             sf = padul_sf[i],
                                             tc = padul_tmp[i] + 
                                               padul_anomalies[[k]][i])$pet_mm
                   })
  })
```

```{r, echo = FALSE}
tibble::tibble(x = rep(seq_len(365), 3),
               y = c(padul_pet_splashv1[[1]],
                     padul_pet_splashv1[[2]],
                     padul_pet_splashv1[[3]]),
               age = rep(padul$`Age (cal yr BP)`[c(1, 179, 247)], 
                         each = 365) %>%
                 forcats::as_factor()) %>%
  ggplot2::ggplot(ggplot2::aes(x, y)) +
  ggplot2::geom_line(ggplot2::aes(colour = age)) +
  ggplot2::scale_colour_brewer("Age (cal yr BP)", palette = "Set1") +
  ggplot2::labs(x = "[days]",
                y = "PET [mm/day]") +
  ggplot2::theme_bw()
```

```{r, include=knitr::is_latex_output(), echo = FALSE}
knitr::asis_output('\n\n\\newpage')
```

### SPLASH v2.0.0
#### Find shortwave radiation [W/m2] (using SPLASH v1.0.0)

```{r, cache = TRUE, echo = TRUE}
year <- 1961
padul_lat <- 37.0108
#Estimate net longwave radiation (rnl), W/m^2
padul_sw <- c(1, 179, 247) %>%
  purrr::map(function(k) {
    purrr::map_dbl(seq_len(365),
                   function(i) {
                     splash::calc_daily_solar(lat = padul_lat,
                                              n = i,
                                              elv = padul_elv,
                                              y = year,
                                              sf = padul_sf[i],
                                              tc = padul_tmp[i] + 
                                                padul_anomalies[[k]][i])$rnl_w.m2
                   })
  })
```

#### Padul soil data
```{r}
padul_soil_data <-c(sand = 0, # sand(perc)
                    clay = 0, # clay(perc)
                    OM = 0, # organic matter(perc)
                    gravel = 0, # coarse-fragments-fraction(perc)
                    bulk_dens = NA, # bulk density(g cm-3), bd
                    maxdepth = 0) # depth
```

#### Run SPLASH
```{r}
padul_pet_splashv2 <- 1:3 %>%
  purrr::map(function(k) {
    # Create core time series object: solar radiation (sw), temperature(tc), and precipitation (pn)
    core <- tibble::tibble(
      time = lubridate::as_date(lubridate::ymd("1961-01-01"):lubridate::ymd("1961-12-31")),
      sw_in = padul_sw[[k]],
      tc = padul_tmp + padul_anomalies[[k]],
      pn = padul_pre
    ) %>%
      tidyr::pivot_longer(c(sw_in, tc, pn), "id") %>%
      tsbox::ts_xts()
    
    # Combine core data with soil data for Padul
    padul_data <- list(core = core,
                       lat = padul_lat,
                       elev = padul_elv,
                       slop = 0,
                       asp = 0,
                       soil_data = padul_soil_data,
                       Au = 0,
                       resolution = 250.)
    
    # Run SPLASH and return PET
    aux <- padul_data %$% 
      rsplash::splash.point(
        sw_in = core$sw_in,     # shortwave radiation W/m2
        tc = core$tc,		        # air temperature C
        pn = core$pn,           # precipitation mm
        lat = lat,		          # latitude deg
        elev = elev,		        # elevation masl
        slop = slop,	          # slope deg
        asp = asp,		          # aspect deg
        soil_data = soil_data, 	# soil data: sand,clay,som in w/w %. Gravel v/v %, bulk density g/cm3, and depth to the bedrock (m)**
        Au = Au,		            # upslope area m2
        resolution = resolution # resolution pixel dem used to get Au
      )
    aux
    # (aux$pet %>%
    #   as.numeric() +
    # aux$aet %>%
    #   as.numeric())
  })
```

```{r, echo = FALSE}
tibble::tibble(x = rep(seq_len(365), 3),
               y = c(padul_pet_splashv2[[1]]$pet %>%
                       as.numeric(),
                     padul_pet_splashv2[[2]]$pet %>%
                       as.numeric(),
                     padul_pet_splashv2[[3]]$pet %>%
                       as.numeric()),
               age = rep(padul$`Age (cal yr BP)`[c(1, 179, 247)], 
                         each = 365) %>%
                 forcats::as_factor()) %>%
  ggplot2::ggplot(ggplot2::aes(x, y)) +
  ggplot2::geom_line(ggplot2::aes(colour = age)) +
  ggplot2::scale_colour_brewer("Age (cal yr BP)", palette = "Set1") +
  ggplot2::labs(x = "[days]",
                y = "PET [mm/day]") +
  ggplot2::theme_bw()
```

### Comparisons
<!-- #### `r age = padul[1, 1]` -->
```{r, echo = FALSE}
k <- 1
tibble::tibble(x = rep(seq_len(365), 2),
               y = c(padul_pet_splashv1[[k]],
                     padul_pet_splashv2[[k]]$pet %>%
                       as.numeric()),
               SPLASH = rep(c("v1.0.0", "v2.0.0"), 
                         each = 365)) %>%
  ggplot2::ggplot(ggplot2::aes(x, y)) +
  ggplot2::geom_line(ggplot2::aes(colour = SPLASH)) +
  ggplot2::scale_colour_brewer("SPLASH", palette = "Set1") +
  ggplot2::labs(x = "[days]",
                y = "PET [mm/day]",
                title = paste0("age = ", padul[1, 1], "cal yr BP")) +
  ggplot2::theme_bw()
```

<!-- #### `r age = padul[179, 1]` -->
```{r, echo = FALSE}
k <- 2
tibble::tibble(x = rep(seq_len(365), 2),
               y = c(padul_pet_splashv1[[k]],
                     padul_pet_splashv2[[k]]$pet %>%
                       as.numeric()),
               SPLASH = rep(c("v1.0.0", "v2.0.0"), 
                         each = 365)) %>%
  ggplot2::ggplot(ggplot2::aes(x, y)) +
  ggplot2::geom_line(ggplot2::aes(colour = SPLASH)) +
  ggplot2::scale_colour_brewer("SPLASH", palette = "Set1") +
  ggplot2::labs(x = "[days]",
                y = "PET [mm/day]",
                title = paste0("age = ", padul[179, 1], "cal yr BP")) +
  ggplot2::theme_bw()
```


<!-- #### `r age = padul[247, 1]` -->
```{r, echo = FALSE}
k <- 3
tibble::tibble(x = rep(seq_len(365), 2),
               y = c(padul_pet_splashv1[[k]],
                     padul_pet_splashv2[[k]]$pet %>%
                       as.numeric()),
               SPLASH = rep(c("v1.0.0", "v2.0.0"), 
                         each = 365)) %>%
  ggplot2::ggplot(ggplot2::aes(x, y)) +
  ggplot2::geom_line(ggplot2::aes(colour = SPLASH)) +
  ggplot2::scale_colour_brewer("SPLASH", palette = "Set1") +
  ggplot2::labs(x = "[days]",
                y = "PET [mm/day]",
                title = paste0("age = ", padul[247, 1], "cal yr BP")) +
  ggplot2::theme_bw()
```

```{r, echo = FALSE, eval = FALSE}
padul_data <- list(#date = (1950 + padul$`Age (cal yr BP)` %>%
                     # .[c(1, 179, 247)]) %>%
                     # lubridate::as_date(paste0("-01-01")),
                   # sw_in = padul_sw,
                   # tc = padul_anomalies %>%
                   #   .[c(1, 179, 247)] %>%
                   #   purrr::map(~.x + padul_tmp),
                   # pn = padul_pre,
                   lat = padul_lat,
                   elev = padul_elv,
                   slop = 0,
                   asp = 0,
                   soil_data = padul_soil_data,
                   Au = 0,
                   resolution = 250.)
```

```{r, include=knitr::is_latex_output(), echo = FALSE}
knitr::asis_output('\n\n\\newpage')
```

## Calculate corrected Precipitation

<!-- Using corrected MI and PET (calculated from modern temperature [CRU TS 4.04] and Padul temperature anomalies). -->

$$\text{corrected P}_\text{ann} = \text{MI} \times \text{PET}_\text{ann}$$

```{r, echo = FALSE}
padul2 <- tibble::tibble(age_calBP = padul$`Age (cal yr BP)`,
                         past_temp = rowMeans(padul[, c("T_djf", "T_jja")]),
                         past_co2 = padul$`Age (cal yr BP)` %>%
                           purrr::map_dbl(codos::past_co2),
                         modern_co2 = tibble::tibble(age = 1950 - c(1961:1990),
                                                     co2 = age %>% 
                                                       purrr::map_dbl(codos::past_co2)) %>%
                           .$co2 %>%
                           mean(), # 340,
                         present_t = rowMeans(padul[, c("T_djf", "T_jja")]), # modern_tmp, 
                         recon_mi = padul$MI)
padul2$corrected_mi <- codos::corrected_mi(padul2$present_t,
                                           padul2$past_temp,
                                           padul2$recon_mi,
                                           padul2$modern_co2,
                                           padul2$past_co2)
padul_corrected_pr_splashv1 <- seq_along(padul_pet_splashv1) %>%
  purrr::map_dbl(~sum(padul_pet_splashv1[.x][[1]], na.rm = TRUE) * padul2$corrected_mi[.x])
padul_corrected_pr_splashv2 <- seq_along(padul_pet_splashv2) %>%
  purrr::map_dbl(~sum(padul_pet_splashv2[[.x]]$pet %>%
                       as.numeric(), 
                      na.rm = TRUE) * padul2$corrected_mi[.x])
```

#### SPLASH v1.0.0
```{r, echo = FALSE}
padul2 %>%
  dplyr::slice(ref_idx) %>%
  purrr::map_df(mean) %>%
  dplyr::mutate(age_calBP = NA) %>%
  dplyr::bind_rows(padul2 %>%
                     dplyr::slice(179, 247)) %>%
  dplyr::mutate(corrected_P_ann = padul_corrected_pr_splashv1) %>%
  knitr::kable("pandoc")
```

#### SPLASH v2.0.0
```{r, echo = FALSE}
padul2 %>%
  dplyr::slice(ref_idx) %>%
  purrr::map_df(mean) %>%
  dplyr::mutate(age_calBP = NA) %>%
  dplyr::bind_rows(padul2 %>%
                     dplyr::slice(179, 247)) %>%
  dplyr::mutate(corrected_P_ann = padul_corrected_pr_splashv2) %>%
  knitr::kable("pandoc")
```





```{r, eval = FALSE, echo = FALSE}
k <- 1
core <- tibble::tibble(
  time = lubridate::as_date(lubridate::ymd("1961-01-01"):lubridate::ymd("1961-12-31")),
  sw_in = padul_sw[[k]],
  tc = padul_tmp + padul_anomalies[[k]],
  pn = padul_pre
) %>%
  tidyr::pivot_longer(c(sw_in, tc, pn), "id") %>%
  tsbox::ts_xts()

padul_data <- list(core = core,
                   lat = padul_lat,
                   elev = padul_elv,
                   slop = 0,
                   asp = 0,
                   soil_data = padul_soil_data,
                   Au = 0,
                   resolution = 250.)

run1 <- padul_data %$% 
  rsplash::splash.point(
    sw_in = core$sw_in,     # shortwave radiation W/m2
    tc = core$tc,		        # air temperature C
    pn = core$pn,           # precipitation mm
    lat = lat,		          # latitude deg
    elev = elev,		        # elevation masl
    slop = slop,	          # slope deg
    asp = asp,		          # aspect deg
    soil_data = soil_data, 	# soil data: sand,clay,som in w/w %. Gravel v/v %, bulk density g/cm3, and depth to the bedrock (m)**
    Au = Au,		            # upslope area m2
    resolution = resolution # resolution pixel dem used to get Au
  )

run1 <- Bourne %$% 
  rsplash::splash.point(
    sw_in = forcing$sw_in, # shortwave radiation W/m2
    tc = forcing$Ta,		   # air temperature C
    pn = forcing$P, # precipitation mm
    lat = md$latitude,		 # latitude deg
    elev = md$elev_m,		   # elevation masl
    slop = md$slop_250m,	 # slope deg
    asp = md$asp_250m,		 # aspect deg
    soil_data = soil, 		 # soil data: sand,clay,som in w/w %. Gravel v/v %, bulk density g/cm3, and depth to the bedrock (m)**
    Au = md$Aups_250m,		 # upslope area m2
    resolution = 250.0  	 # resolution pixel dem used to get Au
  )

solar <- splash::calc_daily_solar(lat = 37.0108, 
                                  n = i, 
                                  elv = padul_elv, 
                                  y = year, 
                                  sf = padul_sf[i], 
                                  tc = padul_tmp[i] + 
                                       padul_anomalies[[k]][i])$rnl_w.m2
```
